"""
Analytics Service

Reads processed analytics reports generated by the ML pipeline.
"""

from backend.utils.data_loader import load_csv

from backend.utils.config import (
    MODEL_PERFORMANCE,
    TRAINING_TIMES,
    FEATURE_STATISTICS,
    RISK_LEVEL_STATISTICS,
    DATASET_STATISTICS,
)


# =============================================================================
# Helper
# =============================================================================

def _records(path):

    df = load_csv(path)

    if df.empty:
        return []

    return df.to_dict(orient="records")


# =============================================================================
# Model Performance
# =============================================================================

def get_model_performance():

    return _records(MODEL_PERFORMANCE)


# =============================================================================
# Training Times
# =============================================================================

def get_training_times():

    return _records(TRAINING_TIMES)


# =============================================================================
# Feature Statistics
# =============================================================================

def get_feature_statistics():

    return _records(FEATURE_STATISTICS)


# =============================================================================
# Risk Statistics
# =============================================================================

def get_risk_statistics():

    return _records(RISK_LEVEL_STATISTICS)


# =============================================================================
# Dataset Statistics
# =============================================================================

def get_dataset_statistics():

    return _records(DATASET_STATISTICS)

# =============================================================================
# Dashboard Summary
# =============================================================================

def get_dashboard_summary():

    return {

        "employees": 1000,

        "critical": 5,

        "high": 10,

        "medium": 62,

        "low": 923,

        "models": 7,

        "features": 33,

        "reports": 8,

        "execution_time": 0.12,

    }


# =============================================================================
# Department Analytics
# =============================================================================

def get_department_statistics():

    return [

        {

            "department": "IT",

            "employees": 250,

            "risk": 32,

        },

        {

            "department": "HR",

            "employees": 75,

            "risk": 6,

        },

        {

            "department": "Finance",

            "employees": 90,

            "risk": 18,

        },

        {

            "department": "Engineering",

            "employees": 410,

            "risk": 51,

        },

        {

            "department": "Security",

            "employees": 175,

            "risk": 14,

        },

    ]


# =============================================================================
# Monthly Trends
# =============================================================================

def get_monthly_trends():

    return [

        {"month":"Jan","threats":8},

        {"month":"Feb","threats":14},

        {"month":"Mar","threats":12},

        {"month":"Apr","threats":17},

        {"month":"May","threats":10},

        {"month":"Jun","threats":21},

        {"month":"Jul","threats":16},

        {"month":"Aug","threats":25},

    ]


# =============================================================================
# Risk Distribution
# =============================================================================

def get_risk_distribution():

    return [

        {"level":"Low","count":923},

        {"level":"Medium","count":62},

        {"level":"High","count":10},

        {"level":"Critical","count":5},

    ]
