"""
Explainability Service

Reads explainability reports generated by the ML pipeline.
"""

from backend.utils.data_loader import load_csv
from backend.utils.config import (
    EMPLOYEE_EXPLANATIONS,
    FEATURE_IMPORTANCE,
    TOP_BEHAVIORAL_FACTORS,
)


# =============================================================================
# Helper
# =============================================================================

def _records(path):
    """
    Read a report safely.
    """

    df = load_csv(path)

    if df.empty:
        return []

    return df.to_dict(orient="records")


# =============================================================================
# Feature Importance
# =============================================================================

def get_feature_importance():
    """
    Returns feature importance generated by the ML pipeline.
    """

    return _records(FEATURE_IMPORTANCE)


# =============================================================================
# Top Behavioral Factors
# =============================================================================

def get_top_behavioral_factors():
    """
    Returns top behavioural factors generated by the ML pipeline.
    """

    return _records(TOP_BEHAVIORAL_FACTORS)


# =============================================================================
# Employee Explanation
# =============================================================================

def get_employee_explanation(employee_id: str):

    df = load_csv(EMPLOYEE_EXPLANATIONS)

    if df.empty:
        return None

    employee_id = employee_id.upper()

    # Detect employee column automatically
    possible_columns = [
        "employee",
        "employee_id",
        "user",
        "username",
    ]

    employee_column = None

    for col in possible_columns:
        if col in df.columns:
            employee_column = col
            break

    if employee_column is None:
        return None

    result = df[
        df[employee_column]
        .astype(str)
        .str.upper()
        == employee_id
    ]

    if result.empty:
        return None

    return result.iloc[0].to_dict()
