"""
Reports Service

Live report generation for the Insider Threat Behavioral Intelligence System.

IMPORTANT
---------
Reports must not blindly depend on stale pre-generated CSV files.

The canonical runtime flow is:

    ML Employee Intelligence
            ↓
    Threat / Risk Data
            ↓
    Investigation Data
            ↓
    Report Generation
            ↓
    CSV Download

Existing configured report files are preserved for compatibility.

For risk/threat/investigation reports, the service refreshes the
report from the current runtime data before returning/downloading it.
"""

from __future__ import annotations

import csv
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from fastapi import HTTPException
from fastapi.responses import FileResponse

from backend.utils.config import REPORT_FILES
from backend.utils.data_loader import load_csv

# Canonical live Threat Center source.
#
# This is important because Threat Center is already verified to return
# the current ML-derived employee intelligence.
from backend.services.threat_service import get_all_threats

# Investigation source.
#
# The current investigation service still contains the existing
# demonstration cases, but we include them in reports so that the
# downloaded investigation report reflects the current investigation
# state rather than ignoring it completely.
from backend.services.investigation_service import get_all_cases
from backend.services.employee_service import get_all_employee_intelligence_service


# =============================================================================
# Constants
# =============================================================================

LIVE_REPORT_KEYWORDS = (
    "risk",
    "threat",
    "suspicious",
    "high_risk",
    "high-risk",
    "investigation",
    "insider",
    "behavioral",
    "behavioural",
)

INVESTIGATION_KEYWORDS = (
    "investigation",
    "case",
    "incident",
)

RISK_KEYWORDS = (
    "risk",
    "threat",
    "suspicious",
    "high_risk",
    "high-risk",
    "insider",
    "behavioral",
    "behavioural",
)


# =============================================================================
# Utility Helpers
# =============================================================================

def _utc_now() -> str:
    return "2011-05-31 00:00:00 UTC"


def _normalise_report_name(report_name: str) -> str:
    """
    Normalise a report identifier for matching.
    """
    return str(report_name or "").strip().lower()


def _report_identifier(report_name: str, path: Path | None = None) -> str:
    """
    Build a combined identifier from report name and filename.
    """
    name_part = _normalise_report_name(report_name)

    path_part = ""
    if path is not None:
        path_part = _normalise_report_name(path.name)

    return f"{name_part} {path_part}".strip()


def _is_investigation_report(
    report_name: str,
    path: Path | None = None,
) -> bool:
    """
    Determine whether a configured report represents investigations/cases.
    """
    identifier = _report_identifier(report_name, path)

    return any(
        keyword in identifier
        for keyword in INVESTIGATION_KEYWORDS
    )


def _is_live_risk_report(
    report_name: str,
    path: Path | None = None,
) -> bool:
    """
    Determine whether a report should be generated from live
    ML/risk/threat data.
    """
    identifier = _report_identifier(report_name, path)

    return any(
        keyword in identifier
        for keyword in LIVE_REPORT_KEYWORDS
    )


def _safe_value(value: Any) -> Any:
    """
    Convert values into CSV-safe primitive values.
    """
    if value is None:
        return ""

    if isinstance(value, (list, tuple, set)):
        return ", ".join(
            str(item)
            for item in value
        )

    if isinstance(value, dict):
        return str(value)

    return value


def _records_from_path(path: Path) -> list[dict[str, Any]]:
    """
    Safely read an existing CSV report.

    This is retained for reports that are still intentionally
    generated by the existing offline pipeline.
    """
    if not path.exists():
        return []

    try:
        df = load_csv(path)
    except Exception:
        return []

    if df is None or df.empty:
        return []

    records = df.to_dict(orient="records")

    return [
        {
            key: _safe_value(value)
            for key, value in record.items()
        }
        for record in records
    ]


# =============================================================================
# Live Threat / Risk Report
# =============================================================================

def _get_live_threat_records() -> list[dict[str, Any]]:
    """
    Get the current ML-derived Threat Center records.

    This deliberately uses the same service as Threat Center.

    Therefore:

        Dashboard
        Threat Center
        Reports

    can all consume the same current risk representation.
    """
    try:
        records = get_all_threats()
    except Exception:
        return []

    if not records:
        return []

    result: list[dict[str, Any]] = []

    for record in records:
        if not isinstance(record, dict):
            continue

        result.append(
            {
                "generated_at": _utc_now(),
                "created_at": record.get("created_at") or get_cert_date_for_user(record.get("user"), record.get("rank")),
                "rank": record.get("rank"),
                "user": record.get("user"),
                "employee_name": record.get(
                    "employee_name",
                    record.get("user"),
                ),
                "employee_id": record.get("employee_id"),
                "department": record.get("department"),
                "risk_score": record.get("risk_score"),
                "risk_level": record.get("risk_level"),
                "severity": record.get("severity"),
                "status": record.get("status"),
                "threat_type": record.get("threat_type"),
                "description": record.get("description"),
                "evidence": record.get("evidence"),
                "models_triggered": record.get(
                    "models_triggered"
                ),
                "suspicious_count": record.get(
                    "suspicious_count"
                ),
                "consensus_percentage": record.get(
                    "consensus_percentage"
                ),
                "weighted_score": record.get(
                    "weighted_score"
                ),

                # Individual model predictions
                "isolation_forest_prediction": record.get(
                    "isolation_forest_prediction"
                ),
                "isolation_forest_score": record.get(
                    "isolation_forest_score"
                ),

                "one_class_svm_prediction": record.get(
                    "one_class_svm_prediction"
                ),
                "one_class_svm_score": record.get(
                    "one_class_svm_score"
                ),

                "lof_prediction": record.get(
                    "lof_prediction"
                ),
                "lof_score": record.get(
                    "lof_score"
                ),

                "elliptic_envelope_prediction": record.get(
                    "elliptic_envelope_prediction"
                ),
                "elliptic_envelope_score": record.get(
                    "elliptic_envelope_score"
                ),

                "pca_prediction": record.get(
                    "pca_prediction"
                ),
                "pca_score": record.get(
                    "pca_score"
                ),

                "dbscan_prediction": record.get(
                    "dbscan_prediction"
                ),
                "dbscan_score": record.get(
                    "dbscan_score"
                ),

                "kmeans_prediction": record.get(
                    "kmeans_prediction"
                ),
                "kmeans_score": record.get(
                    "kmeans_score"
                ),
            }
        )

    result.sort(
        key=lambda item: (
            -float(
                item.get("risk_score")
                or 0
            ),
            int(
                item.get("rank")
                or 999999
            ),
        )
    )

    return result


# =============================================================================
# Live Investigation Report
# =============================================================================

def _get_live_investigation_records() -> list[dict[str, Any]]:
    """
    Get the current investigation cases.

    The investigation service currently maintains the application's
    investigation state. We read it at report-generation time so
    status/assignment/notes changes are reflected.
    """
    try:
        cases = get_all_cases()
    except Exception:
        return []

    if not cases:
        return []

    generated_at = _utc_now()

    records: list[dict[str, Any]] = []

    for case in cases:
        if not isinstance(case, dict):
            continue

        evidence = case.get("evidence", [])

        if isinstance(evidence, list):
            evidence_text = ", ".join(
                str(item)
                for item in evidence
            )
        else:
            evidence_text = str(
                evidence or ""
            )

        records.append(
            {
                "generated_at": generated_at,
                "case_id": case.get("id"),
                "employee": case.get("employee"),
                "department": case.get("department"),
                "risk_score": case.get("risk_score"),
                "risk_level": case.get("risk_level"),
                "prediction": case.get("prediction"),
                "status": case.get("status"),
                "assigned_to": case.get("assigned_to"),
                "created_at": case.get("created_at"),
                "last_updated": case.get("last_updated"),
                "evidence": evidence_text,
                "notes": case.get("notes"),
            }
        )

    records.sort(
        key=lambda item: -float(
            item.get("risk_score")
            or 0
        )
    )

    return records


# =============================================================================
# Combined Investigation + Risk Report
# =============================================================================

def _get_combined_investigation_report() -> list[dict[str, Any]]:
    """
    Combine investigation information with the canonical live
    Threat Center risk data where employee identity can be matched.

    This gives downloaded reports more useful information than the
    old static CSV-only implementation.
    """
    threats = _get_live_threat_records()
    investigations = _get_live_investigation_records()

    threat_by_user: dict[str, dict[str, Any]] = {}

    for threat in threats:
        user = str(
            threat.get("user")
            or ""
        ).strip().lower()

        if user:
            threat_by_user[user] = threat

    records: list[dict[str, Any]] = []

    for investigation in investigations:
        employee = str(
            investigation.get("employee")
            or ""
        ).strip()

        employee_key = employee.lower()

        matching_threat = threat_by_user.get(
            employee_key
        )

        # If the investigation employee is a CERT user ID,
        # we can directly match it.
        #
        # For demonstration cases such as John Carter,
        # there may be no CERT user ID yet. In that case
        # we preserve the investigation record instead of
        # fabricating an identity.
        live_risk = matching_threat or {}

        records.append(
            {
                "generated_at": investigation.get(
                    "generated_at"
                ),

                "case_id": investigation.get(
                    "case_id"
                ),

                "employee": employee,

                "user": live_risk.get(
                    "user",
                    "",
                ),

                "department": investigation.get(
                    "department"
                ),

                "risk_score": (
                    live_risk.get(
                        "risk_score"
                    )
                    if live_risk
                    else investigation.get(
                        "risk_score"
                    )
                ),

                "risk_level": (
                    live_risk.get(
                        "risk_level"
                    )
                    if live_risk
                    else investigation.get(
                        "risk_level"
                    )
                ),

                "prediction": investigation.get(
                    "prediction"
                ),

                "threat_type": live_risk.get(
                    "threat_type",
                    "",
                ),

                "status": investigation.get(
                    "status"
                ),

                "assigned_to": investigation.get(
                    "assigned_to"
                ),

                "created_at": investigation.get(
                    "created_at"
                ),

                "last_updated": investigation.get(
                    "last_updated"
                ),

                "evidence": investigation.get(
                    "evidence"
                ),

                "notes": investigation.get(
                    "notes"
                ),

                "models_triggered": live_risk.get(
                    "models_triggered",
                    "",
                ),

                "suspicious_count": live_risk.get(
                    "suspicious_count",
                    "",
                ),

                "consensus_percentage": live_risk.get(
                    "consensus_percentage",
                    "",
                ),

                "weighted_score": live_risk.get(
                    "weighted_score",
                    "",
                ),
            }
        )

    return records


# =============================================================================
# CSV Generation
# =============================================================================

def _write_csv(
    records: list[dict[str, Any]],
    filename_prefix: str,
) -> Path:
    """
    Create a temporary CSV file for downloading.

    The file is generated at request time, so the user receives
    the current report rather than an old artifact.
    """
    timestamp = datetime.now(
        timezone.utc
    ).strftime("%Y%m%d_%H%M%S_%f")

    safe_prefix = (
        filename_prefix
        .replace("/", "_")
        .replace("\\", "_")
        .replace(" ", "_")
    )

    path = (
        Path(tempfile.gettempdir())
        / f"{safe_prefix}_{timestamp}.csv"
    )

    if not records:
        with path.open(
            "w",
            newline="",
            encoding="utf-8",
        ) as file:
            writer = csv.writer(file)

            writer.writerow(
                [
                    "generated_at",
                    "message",
                ]
            )

            writer.writerow(
                [
                    _utc_now(),
                    "No records available.",
                ]
            )

        return path

    # Collect all columns while preserving the order
    # in which they first appear.
    fieldnames: list[str] = []

    for record in records:
        for key in record.keys():
            if key not in fieldnames:
                fieldnames.append(key)

    with path.open(
        "w",
        newline="",
        encoding="utf-8-sig",
    ) as file:
        writer = csv.DictWriter(
            file,
            fieldnames=fieldnames,
            extrasaction="ignore",
        )

        writer.writeheader()

        for record in records:
            writer.writerow(
                {
                    key: _safe_value(
                        record.get(key)
                    )
                    for key in fieldnames
                }
            )

    return path


def _get_top_100_suspicious_records() -> list[dict[str, Any]]:
    """
    Canonical Top 100 Suspicious employees dataset.
    Returns EXACTLY 100 records (Ranks 1 to 100) sorted by Rank.
    """
    records = get_all_employee_intelligence_service()
    if not records:
        return []

    top_100 = records[:100]
    timestamp = _utc_now()

    result: list[dict[str, Any]] = []

    for item in top_100:
        susp_count = int(item.get("suspicious_count") or 0)
        risk_level = str(item.get("risk_level") or "Low")
        score = float(item.get("risk_score") or 0.0)
        user = str(item.get("user") or "")

        susp_models = []
        for col_prefix, name in [
            ("isolation_forest", "Isolation Forest"),
            ("one_class_svm", "One-Class SVM"),
            ("lof", "LOF"),
            ("elliptic_envelope", "Elliptic Envelope"),
            ("pca", "PCA"),
            ("dbscan", "DBSCAN"),
            ("kmeans", "K-Means"),
        ]:
            if str(item.get(f"{col_prefix}_prediction") or "").lower() == "suspicious":
                susp_models.append(name)

        models_triggered = ", ".join(susp_models) if susp_models else "No models flagged"
        threat_type = f"{risk_level} Behavioral Anomaly"
        description = f"Employee {user} flagged by {susp_count}/7 unsupervised ML models with weighted risk score {score:.1f}/100."
        evidence = f"{susp_count}/7 Models Flagged, Consensus: {item.get('consensus_percentage', 0.0)}%"

        rec = {
            "generated_at": timestamp,
            "created_at": item.get("created_at") or get_cert_date_for_user(user, item.get("rank")),
            "rank": item.get("rank"),
            "user": user,
            "employee_name": user,
            "employee_id": user,
            "department": "CERT Dataset",
            "risk_score": score,
            "risk_level": risk_level,
            "severity": risk_level,
            "status": "Active" if score >= 80 else "Monitored",
            "threat_type": threat_type,
            "description": description,
            "evidence": evidence,
            "models_triggered": models_triggered,
            "suspicious_count": susp_count,
            "consensus_percentage": item.get("consensus_percentage"),
            "weighted_score": score,
            "isolation_forest_prediction": item.get("isolation_forest_prediction"),
            "isolation_forest_score": item.get("isolation_forest_score"),
            "one_class_svm_prediction": item.get("one_class_svm_prediction"),
            "one_class_svm_score": item.get("one_class_svm_score"),
            "lof_prediction": item.get("lof_prediction"),
            "lof_score": item.get("lof_score"),
            "elliptic_envelope_prediction": item.get("elliptic_envelope_prediction"),
            "elliptic_envelope_score": item.get("elliptic_envelope_score"),
            "pca_prediction": item.get("pca_prediction"),
            "pca_score": item.get("pca_score"),
            "dbscan_prediction": item.get("dbscan_prediction"),
            "dbscan_score": item.get("dbscan_score"),
            "kmeans_prediction": item.get("kmeans_prediction"),
            "kmeans_score": item.get("kmeans_score"),
        }
        result.append(rec)

    return result


# =============================================================================
# Report Data Resolver
# =============================================================================

def _get_live_report_records(
    report_name: str,
    path: Path | None = None,
) -> list[dict[str, Any]] | None:
    """
    Resolve whether a report should use live data.

    Returns:
        list[dict] -> live report
        None        -> use existing configured CSV
    """
    norm_name = _normalise_report_name(report_name)
    norm_path = _normalise_report_name(path.name) if path else ""
    combined = f"{norm_name} {norm_path}"

    if "top_100" in combined or "top 100" in combined:
        return _get_top_100_suspicious_records()

    if _is_investigation_report(
        report_name,
        path,
    ):
        return _get_combined_investigation_report()

    if _is_live_risk_report(
        report_name,
        path,
    ):
        return _get_live_threat_records()

    return None


# =============================================================================
# List Reports
# =============================================================================

def get_available_reports():
    """
    Return all configured reports with their current status.

    Existing report configuration is preserved.
    """
    reports = []

    for name, path in REPORT_FILES.items():
        live = _get_live_report_records(
            name,
            path,
        )

        reports.append(
            {
                "name": name,
                "filename": path.name,
                "exists": (
                    True
                    if live is not None
                    else path.exists()
                ),
                "live": live is not None,
                "generated_at": (
                    _utc_now()
                    if live is not None
                    else None
                ),
                "record_count": (
                    len(live)
                    if live is not None
                    else (
                        len(
                            _records_from_path(
                                path
                            )
                        )
                        if path.exists()
                        else 0
                    )
                ),
            }
        )

    return reports


# =============================================================================
# Single Report
# =============================================================================

def get_report(
    report_name: str,
):
    """
    Return one report.

    Risk/threat/investigation reports are generated from
    current runtime data.

    Other reports continue to use their existing CSV artifacts.
    """
    if report_name not in REPORT_FILES:
        raise HTTPException(
            status_code=404,
            detail="Report not found.",
        )

    path = REPORT_FILES[
        report_name
    ]

    live_records = _get_live_report_records(
        report_name,
        path,
    )

    if live_records is not None:
        return live_records

    return _records_from_path(path)


# =============================================================================
# All Reports
# =============================================================================

def get_all_reports():
    """
    Return all available reports.

    Live reports are recalculated at request time.
    """
    reports: dict[str, list[dict[str, Any]]] = {}

    for name, path in REPORT_FILES.items():
        reports[name] = get_report(name)

    return reports


# =============================================================================
# Download Report
# =============================================================================

def _write_pdf(records: list[dict[str, Any]], title: str) -> Path:
    temp_dir = Path(tempfile.gettempdir())
    output_path = temp_dir / f"{title}_{int(datetime.now().timestamp())}.pdf"
    display_title = title.replace("_", " ").title()

    try:
        from reportlab.lib.pagesizes import letter, landscape
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        )
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib import colors

        doc = SimpleDocTemplate(
            str(output_path),
            pagesize=landscape(letter),
            leftMargin=36,
            rightMargin=36,
            topMargin=36,
            bottomMargin=36,
        )
        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            "ReportTitle",
            parent=styles["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=16,
            leading=20,
            textColor=colors.HexColor("#0f172a"),
        )

        meta_style = ParagraphStyle(
            "ReportMeta",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#475569"),
        )

        story = [
            Paragraph(f"<b>Insider Threat Intelligence System</b> — {display_title}", title_style),
            Spacer(1, 4),
            Paragraph(
                f"Generated on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')} | Total Records: {len(records)}",
                meta_style
            ),
            Spacer(1, 14),
        ]

        if records:
            preferred_columns = [
                ("rank", "Rank"),
                ("user", "Employee ID"),
                ("employee_name", "Name"),
                ("risk_score", "Risk Score"),
                ("risk_level", "Risk Level"),
                ("suspicious_count", "Models Flagged"),
                ("consensus_percentage", "Consensus %"),
                ("status", "Status"),
            ]

            available_keys = list(records[0].keys())

            selected_cols = [
                (k, label) for k, label in preferred_columns
                if k in available_keys
            ]

            if not selected_cols:
                selected_cols = [(k, str(k).replace("_", " ").title()) for k in available_keys[:8]]

            headers = [label for _, label in selected_cols]
            data = [headers]

            # Process ALL records — NO truncation
            for r in records:
                row_vals = []
                for k, _ in selected_cols:
                    val = r.get(k, "")
                    if isinstance(val, float):
                        val_str = f"{val:.1f}"
                    elif val is None:
                        val_str = "—"
                    else:
                        val_str = str(val)[:40]
                    row_vals.append(val_str)
                data.append(row_vals)

            t = Table(data, repeatRows=1)

            t_style = [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#38bdf8")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 9),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 6),
                ("TOPPADDING", (0, 0), (-1, 0), 6),
                ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 1), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 1), (-1, -1), 4),
                ("TOPPADDING", (0, 1), (-1, -1), 4),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ]

            for row_idx in range(1, len(data)):
                bg = colors.HexColor("#f8fafc") if row_idx % 2 == 1 else colors.HexColor("#ffffff")
                t_style.append(("BACKGROUND", (0, row_idx), (-1, row_idx), bg))

            t.setStyle(TableStyle(t_style))
            story.append(t)

        doc.build(story)

    except Exception:
        # Fallback pdf generation if reportlab fails
        with open(output_path, "wb") as f:
            pdf_data = (
                "%PDF-1.4\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n"
                "2 0 obj<</Type/Pages/Count 1/Kids[3 0 R]>>endobj\n"
                "3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R/Resources<<>>>>endobj\n"
                "trailer<</Size 4/Root 1 0 R>>\nstartxref\n149\n%%EOF\n"
            )
            f.write(pdf_data.encode("latin-1"))

    return output_path


def _write_excel(records: list[dict[str, Any]], title: str) -> tuple[Path, str]:
    temp_dir = Path(tempfile.gettempdir())
    output_path = temp_dir / f"{title}_{int(datetime.now().timestamp())}.xlsx"
    try:
        df = pd.DataFrame(records)
        df.to_excel(output_path, index=False, engine="openpyxl")
        return output_path, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    except Exception:
        output_csv = temp_dir / f"{title}_{int(datetime.now().timestamp())}.csv"
        df = pd.DataFrame(records)
        df.to_csv(output_csv, index=False)
        return output_csv, "text/csv"


def download_report(
    report_name: str,
    export_format: str = "csv",
):
    """
    Download a report in CSV, PDF, or Excel format.
    Uses the exact canonical report dataset produced by get_report(report_name).
    """
    if report_name not in REPORT_FILES:
        raise HTTPException(
            status_code=404,
            detail="Report not found.",
        )

    path = REPORT_FILES[report_name]
    records = get_report(report_name)

    if not isinstance(records, list):
        if hasattr(records, "to_dict"):
            records = records.to_dict(orient="records")
        else:
            records = []

    fmt = str(export_format).lower().strip()
    title = path.stem or report_name

    if fmt == "pdf":
        pdf_file = _write_pdf(records, title)
        return FileResponse(
            path=pdf_file,
            filename=f"{title}_report.pdf",
            media_type="application/pdf",
        )
    elif fmt in ["excel", "xlsx"]:
        excel_file, mtype = _write_excel(records, title)
        ext = "xlsx" if mtype != "text/csv" else "csv"
        return FileResponse(
            path=excel_file,
            filename=f"{title}_report.{ext}",
            media_type=mtype,
        )

    # Default CSV
    generated_file = _write_csv(
        records,
        title,
    )
    return FileResponse(
        path=generated_file,
        filename=f"{title}_live.csv",
        media_type="text/csv",
    )


# =============================================================================
# Report Path
# =============================================================================

def get_report_path(
    report_name: str,
):
    """
    Return the configured report path.
    """
    return REPORT_FILES.get(
        report_name
    )
