# -*- coding: utf-8 -*-
"""insider_threat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a5cw8A3Ck7sxBfxUOddFDGyTwQ8JeiYq
"""

!pip install -q kagglehub

import kagglehub
path = kagglehub.dataset_download("andrihjonior/cert-insider-threat-dataset-r4-2")
print("Dataset downloaded to:", path)

import os

BASE = path
DATA_DIR = f"{BASE}/r4.2"
ANSWERS_DIR = f"{BASE}/answers"

print(os.listdir(DATA_DIR))

import pandas as pd
import numpy as np
import joblib
import json
import gc
from functools import reduce
from sklearn.ensemble import IsolationForest

os.makedirs("/content/models", exist_ok=True)
MODEL_DIR = "/content/models"

pd.set_option("mode.chained_assignment", None)

ldap_dir = f"{DATA_DIR}/LDAP"
ldap_files = sorted(os.listdir(ldap_dir))

ldap_frames = []
for f in ldap_files:
    df = pd.read_csv(f"{ldap_dir}/{f}")
    df["snapshot_month"] = f.replace(".csv", "")
    ldap_frames.append(df)

ldap_all = pd.concat(ldap_frames, ignore_index=True)
ldap_all["snapshot_month"] = pd.to_datetime(ldap_all["snapshot_month"], format="%Y-%m")

ldap_latest = (
    ldap_all.sort_values(["user_id", "snapshot_month"])
    .groupby("user_id")
    .agg(role=("role", "last"), department=("department", "last"))
    .reset_index()
    .rename(columns={"user_id": "user"})
)

del ldap_all, ldap_frames
gc.collect()

insiders = pd.read_csv(f"{ANSWERS_DIR}/insiders.csv")
insiders_r42 = insiders[insiders["dataset"] == 4.2]

print("LDAP shape:", ldap_latest.shape)
print("Known r4.2 insiders:", insiders_r42["user"].tolist())

logon = pd.read_csv(f"{DATA_DIR}/logon.csv")
logon["date"] = pd.to_datetime(logon["date"], format="%m/%d/%Y %H:%M:%S", errors="coerce")
logon["day"] = logon["date"].dt.date
logon["hour"] = logon["date"].dt.hour.astype("int8")
logon["dow"] = logon["date"].dt.dayofweek.astype("int8")
logon["is_logon"] = (logon["activity"] == "Logon").astype("int8")
logon["is_logoff"] = (logon["activity"] == "Logoff").astype("int8")
logon["is_after_hours"] = ((logon["hour"] < 6) | (logon["hour"] > 20)).astype("int8")
logon["is_weekend"] = (logon["dow"] >= 5).astype("int8")

logon_daily = logon.groupby(["user", "day"]).agg(
    n_logons=("is_logon", "sum"),
    n_logoffs=("is_logoff", "sum"),
    first_hour=("hour", "min"),
    last_hour=("hour", "max"),
    after_hours_events=("is_after_hours", "sum"),
    n_pcs=("pc", "nunique"),
    is_weekend_activity=("is_weekend", "max"),
).reset_index()

del logon
gc.collect()
print("logon_daily:", logon_daily.shape)

device = pd.read_csv(f"{DATA_DIR}/device.csv")
device["date"] = pd.to_datetime(device["date"], format="%m/%d/%Y %H:%M:%S", errors="coerce")
device["day"] = device["date"].dt.date
device["is_connect"] = (device["activity"] == "Connect").astype("int8")
device["is_disconnect"] = (device["activity"] == "Disconnect").astype("int8")

device_daily = device.groupby(["user", "day"]).agg(
    n_device_connects=("is_connect", "sum"),
    n_device_disconnects=("is_disconnect", "sum"),
).reset_index()

del device
gc.collect()
print("device_daily:", device_daily.shape)

file_ = pd.read_csv(f"{DATA_DIR}/file.csv", usecols=["date", "user", "filename"])
file_["date"] = pd.to_datetime(file_["date"], format="%m/%d/%Y %H:%M:%S", errors="coerce")
file_["day"] = file_["date"].dt.date
file_["ext"] = file_["filename"].str.extract(r"\.(\w+)$")

file_daily = file_.groupby(["user", "day"]).agg(
    n_file_copies=("user", "count"),
    n_distinct_file_types=("ext", "nunique"),
).reset_index()

del file_
gc.collect()
print("file_daily:", file_daily.shape)

chunk_list = []
chunksize = 3_000_000

for chunk in pd.read_csv(f"{DATA_DIR}/http.csv", usecols=["date", "user", "url"], chunksize=chunksize):
    chunk["date"] = pd.to_datetime(chunk["date"], format="%m/%d/%Y %H:%M:%S", errors="coerce")
    chunk["day"] = chunk["date"].dt.date
    chunk["domain"] = chunk["url"].str.extract(r"http://([^/]+)/")

    agg = chunk.groupby(["user", "day"]).agg(
        n_http_requests=("user", "count"),
        n_distinct_domains=("domain", "nunique"),
    ).reset_index()

    chunk_list.append(agg)
    del chunk, agg
    gc.collect()

http_daily = (
    pd.concat(chunk_list, ignore_index=True)
    .groupby(["user", "day"])
    .agg(n_http_requests=("n_http_requests", "sum"), n_distinct_domains=("n_distinct_domains", "max"))
    .reset_index()
)

del chunk_list
gc.collect()
print("http_daily:", http_daily.shape)

email = pd.read_csv(f"{DATA_DIR}/email.csv", usecols=["date", "user", "to", "size", "attachments"])
email["date"] = pd.to_datetime(email["date"], format="%m/%d/%Y %H:%M:%S", errors="coerce")
email["day"] = email["date"].dt.date
email["n_to"] = email["to"].fillna("").str.count(";") + 1
email["has_attachment"] = (email["attachments"] > 0).astype("int8")

email_daily = email.groupby(["user", "day"]).agg(
    n_emails_sent=("user", "count"),
    total_recipients=("n_to", "sum"),
    n_emails_with_attachment=("has_attachment", "sum"),
    total_email_size=("size", "sum"),
).reset_index()

del email
gc.collect()
print("email_daily:", email_daily.shape)

frames = [logon_daily, device_daily, email_daily, file_daily, http_daily]
features_df = reduce(lambda left, right: pd.merge(left, right, on=["user", "day"], how="outer"), frames)
features_df = features_df.fillna(0)

del logon_daily, device_daily, email_daily, file_daily, http_daily, frames
gc.collect()

print("Feature table shape:", features_df.shape)
features_df.head()

base_feature_cols = [c for c in features_df.columns if c not in ["user", "day"]]

features_with_role = features_df.merge(ldap_latest, on="user", how="left")
del features_df
gc.collect()

role_means = features_with_role.groupby("role")[base_feature_cols].transform("mean")
role_stds = features_with_role.groupby("role")[base_feature_cols].transform("std")

for c in base_feature_cols:
    features_with_role[f"{c}_role_zscore"] = (
        (features_with_role[c] - role_means[c]) / (role_stds[c] + 1e-6)
    ).fillna(0)

del role_means, role_stds
gc.collect()

features_with_role = features_with_role.sort_values(["user", "day"])
rolling_cols = ["n_logons", "after_hours_events", "n_device_connects", "n_emails_sent", "n_file_copies"]

for c in rolling_cols:
    features_with_role[f"{c}_7d_avg"] = (
        features_with_role.groupby("user")[c]
        .transform(lambda x: x.rolling(window=7, min_periods=1).mean())
    )
    features_with_role[f"{c}_deviation"] = features_with_role[c] - features_with_role[f"{c}_7d_avg"]

final_df = features_with_role
print("final_df:", final_df.shape)

model_feature_cols = (
    base_feature_cols
    + [f"{c}_role_zscore" for c in base_feature_cols]
    + [f"{c}_deviation" for c in rolling_cols]
)

X = final_df[model_feature_cols].fillna(0).to_numpy()

model = IsolationForest(n_estimators=300, contamination=0.01, random_state=42, n_jobs=-1)
model.fit(X)

final_df["anomaly_score"] = -model.decision_function(X)

min_s, max_s = final_df["anomaly_score"].min(), final_df["anomaly_score"].max()
final_df["risk_score"] = (final_df["anomaly_score"] - min_s) / (max_s - min_s) * 100

def categorize(score):
    if score >= 80: return "Critical"
    elif score >= 60: return "High"
    elif score >= 30: return "Medium"
    else: return "Low"

final_df["risk_category"] = final_df["risk_score"].apply(categorize)

user_risk = (
    final_df.groupby("user")
    .agg(max_daily_risk=("risk_score", "max"), avg_daily_risk=("risk_score", "mean"))
    .sort_values("max_daily_risk", ascending=False)
    .reset_index()
)

insider_users = set(insiders_r42["user"].tolist())
top_n = 50
predicted_top = set(user_risk.head(top_n)["user"].tolist())
hits = predicted_top & insider_users
print(f"Known insiders in top {top_n}: {len(hits)}/{len(insider_users)} — {hits}")

user_risk_list = user_risk["user"].tolist()
for u in insider_users:
    rank = user_risk_list.index(u) + 1 if u in user_risk_list else "not found"
    print(f"  {u}: rank {rank}")

# Save artifacts
joblib.dump(model, f"{MODEL_DIR}/isolation_forest.joblib")
with open(f"{MODEL_DIR}/feature_columns.json", "w") as f:
    json.dump(model_feature_cols, f)

role_stats = final_df.groupby("role")[base_feature_cols].agg(["mean", "std"])
role_stats.to_parquet(f"{MODEL_DIR}/role_stats.parquet")
ldap_latest.to_parquet(f"{MODEL_DIR}/ldap_latest.parquet")
final_df.to_csv(f"{MODEL_DIR}/full_feature_table_scored.csv", index=False)

print("Pipeline complete. Artifacts saved to", MODEL_DIR)

# Check which scenario each poorly-ranked insider belongs to
poor_performers = ["NWT0098", "KPC0073", "IUB0565", "PSF0133", "KRL0501"]
print(insiders_r42[insiders_r42["user"].isin(poor_performers)][["user", "scenario", "details"]])

# Precision@K for a few thresholds — useful for your report/resume
for k in [10, 20, 50, 100]:
    top_k = set(user_risk.head(k)["user"].tolist())
    hits_k = len(top_k & insider_users)
    print(f"Precision@{k}: {hits_k}/{k} ({hits_k/k*100:.1f}%) | Recall@{k}: {hits_k}/{len(insider_users)} ({hits_k/len(insider_users)*100:.1f}%)")

poor_performers = ["NWT0098", "KPC0073", "IUB0565", "PSF0133", "KRL0501", "XHW0498", "RGG0064"]
print(insiders_r42[insiders_r42["user"].isin(poor_performers)][["user", "scenario", "details", "start", "end"]])

anomaly_report = (
    final_df.sort_values("risk_score", ascending=False)
    .loc[:, ["user", "day", "role", "risk_score", "risk_category",
             "after_hours_events", "n_device_connects", "n_emails_sent"]]
    .head(200)
)
anomaly_report.to_csv(f"{MODEL_DIR}/milestone2_anomaly_report.csv", index=False)
print("Saved anomaly report.")

def investigate_user(user_id, day, model_dir=MODEL_DIR, data_dir=DATA_DIR):
    print(f"=== Investigation: {user_id} on {day} ===\n")

    logon = pd.read_csv(f"{data_dir}/logon.csv")
    logon["date"] = pd.to_datetime(logon["date"], format="%m/%d/%Y %H:%M:%S", errors="coerce")
    logon_day = logon[(logon["user"] == user_id) & (logon["date"].dt.date == day)]
    print("LOGON EVENTS:")
    print(logon_day[["date", "activity", "pc"]].to_string(index=False))
    del logon

    device = pd.read_csv(f"{data_dir}/device.csv")
    device["date"] = pd.to_datetime(device["date"], format="%m/%d/%Y %H:%M:%S", errors="coerce")
    device_day = device[(device["user"] == user_id) & (device["date"].dt.date == day)]
    print("\nDEVICE EVENTS:")
    print(device_day[["date", "activity"]].to_string(index=False))
    del device

    gc.collect()

# Example: investigate your top-ranked known insider
investigate_user("MCF0600", final_df[final_df["user"]=="MCF0600"].sort_values("risk_score", ascending=False).iloc[0]["day"])

def normalize(s):
    return (s - s.min()) / (s.max() - s.min() + 1e-9) * 100

final_df["behavioral_component"] = final_df[[f"{c}_deviation" for c in rolling_cols]].abs().mean(axis=1)
final_df["data_access_component"] = final_df["n_file_copies_deviation"].abs()
final_df["access_pattern_component"] = final_df["n_device_connects_deviation"].abs()

final_df["weighted_risk_score"] = (
    0.35 * normalize(final_df["behavioral_component"]) +
    0.20 * normalize(final_df["data_access_component"]) +
    0.10 * normalize(final_df["access_pattern_component"]) +
    0.35 * final_df["risk_score"]  # your ML anomaly score covers remaining categories
)

def peer_comparison(user_id):
    user_row = final_df[final_df["user"] == user_id].sort_values("risk_score", ascending=False).iloc[0]
    role = user_row["role"]
    peer_avg = final_df[final_df["role"] == role][base_feature_cols].mean()
    comparison = pd.DataFrame({
        "user_value": user_row[base_feature_cols],
        "peer_avg": peer_avg
    })
    comparison["deviation"] = comparison["user_value"] - comparison["peer_avg"]
    return comparison.sort_values("deviation", key=abs, ascending=False)

print(peer_comparison("MCF0600").head(10))

print("=== Model Validation Metrics ===\n")
for k in [10, 20, 50, 100]:
    top_k = set(user_risk.head(k)["user"].tolist())
    hits_k = len(top_k & insider_users)
    precision = hits_k / k * 100
    recall = hits_k / len(insider_users) * 100
    print(f"Top {k:>3}: {hits_k:>2}/{k} caught | Precision@{k}: {precision:5.1f}% | Recall@{k}: {recall:5.1f}%")

anomaly_report = (
    final_df.sort_values("risk_score", ascending=False)
    .loc[:, ["user", "day", "role", "risk_score", "risk_category",
             "after_hours_events", "n_device_connects", "n_emails_sent", "n_file_copies"]]
    .head(200)
)

anomaly_report.to_csv(f"{MODEL_DIR}/milestone2_anomaly_report.csv", index=False)
print(f"Saved anomaly report with {len(anomaly_report)} rows to {MODEL_DIR}/milestone2_anomaly_report.csv")
print(anomaly_report.head(15))

def investigate_user(user_id, day=None, data_dir=DATA_DIR, top_n_days=5):
    """
    Investigate a specific user. If `day` is not given, uses their highest-risk day.
    Prints activity timeline across all log sources for that day.
    """
    user_days = final_df[final_df["user"] == user_id].sort_values("risk_score", ascending=False)

    if user_days.empty:
        print(f"No data found for user {user_id}")
        return

    print(f"=== Investigation Report: {user_id} ===")
    print(f"Role: {user_days.iloc[0]['role']}")
    print(f"\nTop {top_n_days} highest-risk days:")
    print(user_days[["day", "risk_score", "risk_category"]].head(top_n_days).to_string(index=False))

    target_day = day if day is not None else user_days.iloc[0]["day"]
    print(f"\n--- Detailed activity on {target_day} ---\n")

    # Logon
    logon = pd.read_csv(f"{data_dir}/logon.csv")
    logon["date"] = pd.to_datetime(logon["date"], format="%m/%d/%Y %H:%M:%S", errors="coerce")
    logon_day = logon[(logon["user"] == user_id) & (logon["date"].dt.date == target_day)]
    print("LOGON EVENTS:")
    print(logon_day[["date", "activity", "pc"]].to_string(index=False) if not logon_day.empty else "  (none)")
    del logon; gc.collect()

    # Device
    device = pd.read_csv(f"{data_dir}/device.csv")
    device["date"] = pd.to_datetime(device["date"], format="%m/%d/%Y %H:%M:%S", errors="coerce")
    device_day = device[(device["user"] == user_id) & (device["date"].dt.date == target_day)]
    print("\nDEVICE EVENTS:")
    print(device_day[["date", "activity"]].to_string(index=False) if not device_day.empty else "  (none)")
    del device; gc.collect()

    # Email
    email = pd.read_csv(f"{data_dir}/email.csv", usecols=["date", "user", "to", "size", "attachments"])
    email["date"] = pd.to_datetime(email["date"], format="%m/%d/%Y %H:%M:%S", errors="coerce")
    email_day = email[(email["user"] == user_id) & (email["date"].dt.date == target_day)]
    print("\nEMAIL EVENTS:")
    print(email_day[["date", "to", "size", "attachments"]].to_string(index=False) if not email_day.empty else "  (none)")
    del email; gc.collect()

    # File
    file_ = pd.read_csv(f"{data_dir}/file.csv", usecols=["date", "user", "filename"])
    file_["date"] = pd.to_datetime(file_["date"], format="%m/%d/%Y %H:%M:%S", errors="coerce")
    file_day = file_[(file_["user"] == user_id) & (file_["date"].dt.date == target_day)]
    print("\nFILE EVENTS:")
    print(file_day[["date", "filename"]].to_string(index=False) if not file_day.empty else "  (none)")
    del file_; gc.collect()

    return {
        "logon": logon_day if 'logon_day' in dir() else None,
        "risk_score": user_days.iloc[0]["risk_score"],
        "risk_category": user_days.iloc[0]["risk_category"],
    }

# Example: investigate your top-ranked known insider
_ = investigate_user("MCF0600")

def normalize(s):
    return (s - s.min()) / (s.max() - s.min() + 1e-9) * 100

# Map available features to the brief's weighted categories
final_df["behavioral_component"] = final_df[[f"{c}_deviation" for c in rolling_cols]].abs().mean(axis=1)
final_df["data_access_component"] = final_df["n_file_copies_deviation"].abs()
final_df["access_pattern_component"] = final_df["n_device_connects_deviation"].abs()

# Weighted formula: Behavioral 35%, Data Access 20%, Access Pattern 10%, ML anomaly score covers
# the remaining categories (privilege misuse, historical events) as a proxy until Milestone 4's
# live RBAC/audit data is available
final_df["weighted_risk_score"] = (
    0.35 * normalize(final_df["behavioral_component"]) +
    0.20 * normalize(final_df["data_access_component"]) +
    0.10 * normalize(final_df["access_pattern_component"]) +
    0.35 * final_df["risk_score"]
)

final_df["weighted_risk_category"] = final_df["weighted_risk_score"].apply(categorize)

weighted_user_risk = (
    final_df.groupby("user")
    .agg(max_weighted_risk=("weighted_risk_score", "max"))
    .sort_values("max_weighted_risk", ascending=False)
    .reset_index()
)

# Re-validate with the new weighted score
top_50_weighted = set(weighted_user_risk.head(50)["user"].tolist())
hits_weighted = top_50_weighted & insider_users
print(f"Weighted score — known insiders in top 50: {len(hits_weighted)}/{len(insider_users)}")
print(hits_weighted)

# Save updated artifacts
final_df.to_csv(f"{MODEL_DIR}/full_feature_table_scored.csv", index=False)
weighted_user_risk.to_csv(f"{MODEL_DIR}/weighted_user_risk_ranking.csv", index=False)
print("\nSaved updated scored table and weighted ranking.")

normalization_stats = {
    "anomaly_score_min": float(final_df["anomaly_score"].min()),
    "anomaly_score_max": float(final_df["anomaly_score"].max()),
    "behavioral_component_min": float(final_df["behavioral_component"].min()),
    "behavioral_component_max": float(final_df["behavioral_component"].max()),
    "data_access_component_min": float(final_df["data_access_component"].min()),
    "data_access_component_max": float(final_df["data_access_component"].max()),
    "access_pattern_component_min": float(final_df["access_pattern_component"].min()),
    "access_pattern_component_max": float(final_df["access_pattern_component"].max()),
}

with open(f"{MODEL_DIR}/normalization_stats.json", "w") as f:
    json.dump(normalization_stats, f)

print("Saved normalization stats:", normalization_stats)

def detect_log_type(df):
    """Identify which CERT log type a dataframe represents, based on its columns."""
    cols = set(df.columns)
    if "url" in cols:
        return "http"
    if "to" in cols and "attachments" in cols:
        return "email"
    if "filename" in cols:
        return "file"
    if "activity" in cols and "pc" in cols:
        sample = df["activity"].dropna().unique()[:5]
        if any(v in ("Logon", "Logoff") for v in sample):
            return "logon"
        elif any(v in ("Connect", "Disconnect") for v in sample):
            return "device"
    raise ValueError(f"Could not identify log type from columns: {cols}")


def build_daily_features(df, log_type):
    """Same feature logic as training, applied to one log type's dataframe."""
    df = df.copy()
    df["date"] = pd.to_datetime(df["date"], format="%m/%d/%Y %H:%M:%S", errors="coerce")
    df["day"] = df["date"].dt.date

    if log_type == "logon":
        df["hour"] = df["date"].dt.hour
        df["dow"] = df["date"].dt.dayofweek
        df["is_logon"] = (df["activity"] == "Logon").astype(int)
        df["is_logoff"] = (df["activity"] == "Logoff").astype(int)
        df["is_after_hours"] = ((df["hour"] < 6) | (df["hour"] > 20)).astype(int)
        df["is_weekend"] = (df["dow"] >= 5).astype(int)
        return df.groupby(["user", "day"]).agg(
            n_logons=("is_logon", "sum"), n_logoffs=("is_logoff", "sum"),
            first_hour=("hour", "min"), last_hour=("hour", "max"),
            after_hours_events=("is_after_hours", "sum"),
            n_pcs=("pc", "nunique"), is_weekend_activity=("is_weekend", "max"),
        ).reset_index()

    elif log_type == "device":
        df["is_connect"] = (df["activity"] == "Connect").astype(int)
        df["is_disconnect"] = (df["activity"] == "Disconnect").astype(int)
        return df.groupby(["user", "day"]).agg(
            n_device_connects=("is_connect", "sum"),
            n_device_disconnects=("is_disconnect", "sum"),
        ).reset_index()

    elif log_type == "email":
        df["n_to"] = df["to"].fillna("").str.count(";") + 1
        df["has_attachment"] = (df["attachments"] > 0).astype(int)
        return df.groupby(["user", "day"]).agg(
            n_emails_sent=("user", "count"), total_recipients=("n_to", "sum"),
            n_emails_with_attachment=("has_attachment", "sum"),
            total_email_size=("size", "sum"),
        ).reset_index()

    elif log_type == "file":
        df["ext"] = df["filename"].str.extract(r"\.(\w+)$")
        return df.groupby(["user", "day"]).agg(
            n_file_copies=("user", "count"), n_distinct_file_types=("ext", "nunique"),
        ).reset_index()

    elif log_type == "http":
        df["domain"] = df["url"].str.extract(r"http://([^/]+)/")
        return df.groupby(["user", "day"]).agg(
            n_http_requests=("user", "count"), n_distinct_domains=("domain", "nunique"),
        ).reset_index()


def predict_from_csv(csv_paths, model_dir="/content/models"):
    """
    csv_paths: a single path (str) or a list of paths, each shaped like one CERT log type
               (logon.csv, device.csv, email.csv, file.csv, or http.csv format).
    Returns a dataframe with risk_score and risk_category per user-day.
    """
    if isinstance(csv_paths, str):
        csv_paths = [csv_paths]

    # Load saved artifacts
    model = joblib.load(f"{model_dir}/isolation_forest.joblib")
    with open(f"{model_dir}/feature_columns.json") as f:
        feature_cols = json.load(f)
    with open(f"{model_dir}/normalization_stats.json") as f:
        norm_stats = json.load(f)
    role_stats = pd.read_parquet(f"{model_dir}/role_stats.parquet")
    ldap_latest = pd.read_parquet(f"{model_dir}/ldap_latest.parquet")

    # Build features per file, merge
    daily_frames = []
    for path in csv_paths:
        raw = pd.read_csv(path)
        log_type = detect_log_type(raw)
        print(f"{path} → detected as: {log_type}")
        daily_frames.append(build_daily_features(raw, log_type))
        del raw
        gc.collect()

    features_df = reduce(lambda l, r: pd.merge(l, r, on=["user", "day"], how="outer"), daily_frames)
    features_df = features_df.fillna(0)

    base_feature_cols = [c for c in features_df.columns if c not in ["user", "day"]]

    # Fill in any base columns missing entirely (e.g., only logon.csv was given)
    for c in [c for c in feature_cols if not (c.endswith("_role_zscore") or c.endswith("_deviation"))]:
        if c not in features_df.columns:
            features_df[c] = 0

    # Join role context
    features_df = features_df.merge(ldap_latest, on="user", how="left")

    # Role z-scores using SAVED training stats (not recomputed on new data)
    for c in base_feature_cols:
        mean_col = (c, "mean")
        std_col = (c, "std")
        if mean_col in role_stats.columns:
            role_mean_map = role_stats[mean_col].to_dict()
            role_std_map = role_stats[std_col].to_dict()
            features_df[f"{c}_role_zscore"] = features_df.apply(
                lambda r: (r[c] - role_mean_map.get(r["role"], 0)) / (role_std_map.get(r["role"], 1) + 1e-6)
                if pd.notna(r["role"]) else 0, axis=1
            )
        else:
            features_df[f"{c}_role_zscore"] = 0

    # Rolling deviation features — with only new/limited data, default to 0 (no historical baseline)
    rolling_cols = ["n_logons", "after_hours_events", "n_device_connects", "n_emails_sent", "n_file_copies"]
    for c in rolling_cols:
        if f"{c}_deviation" not in features_df.columns:
            features_df[f"{c}_deviation"] = 0

    # Align exactly to training feature order
    for c in feature_cols:
        if c not in features_df.columns:
            features_df[c] = 0
    X = features_df[feature_cols].fillna(0).to_numpy()

    # Predict using saved model
    anomaly_scores = -model.decision_function(X)

    # Normalize using SAVED training min/max, not new data's min/max
    min_s, max_s = norm_stats["anomaly_score_min"], norm_stats["anomaly_score_max"]
    risk_score = np.clip((anomaly_scores - min_s) / (max_s - min_s + 1e-9) * 100, 0, 100)

    features_df["anomaly_score"] = anomaly_scores
    features_df["risk_score"] = risk_score
    features_df["risk_category"] = features_df["risk_score"].apply(
        lambda s: "Critical" if s >= 80 else "High" if s >= 60 else "Medium" if s >= 30 else "Low"
    )

    return features_df.sort_values("risk_score", ascending=False)

# Example: score a new CSV (or list of CSVs covering different log types)
result = predict_from_csv([f"{DATA_DIR}/logon.csv"])  # swap with your own new file(s)

print(result[["user", "day", "role", "risk_score", "risk_category"]].head(20))

# Save flagged (High/Critical) users as a report
flagged = result[result["risk_category"].isin(["High", "Critical"])]
flagged.to_csv(f"{MODEL_DIR}/flagged_threats_report.csv", index=False)
print(f"\n{len(flagged)} user-days flagged as High/Critical risk.")

