"""Tests for the schema migrations.

WHY THESE EXIST
---------------
The schema used to be created with `Base.metadata.create_all()`. That function
creates tables that do not exist, and does NOTHING to tables that do. So adding a
column to an existing model produced a clean startup and then a crash on the first
INSERT:

    psycopg2.errors.UndefinedColumn:
      column "session_count" of relation "daily_features" does not exist

It happened twice. Once after seven minutes of streaming 13.9 GB of http.csv.

Alembic fixes it - but only if the migrations are actually correct, and a migration
is a piece of code like any other. An untested migration is a production outage
with a delay fuse. These tests are that fuse being cut.
"""

from __future__ import annotations

import re

import pytest
from sqlalchemy import inspect, text

from backend.app.database import engine


def test_database_is_at_the_migration_the_code_expects() -> None:
    """The app must refuse to run against a stale schema.

    An application that boots happily against the wrong schema is WORSE than one
    that refuses to boot. The first fails later - in production, mid-INSERT, on
    real data. The second fails immediately, with an instruction.
    """
    from backend.app.schema import schema_is_current

    ok, message = schema_is_current()
    assert ok, f"database schema is not current: {message}"


def test_models_and_database_have_not_drifted() -> None:
    """`alembic check` must be clean.

    This is the test that would have caught BOTH historical failures before they
    ever reached a human. If a model gains a column and nobody writes a migration,
    autogenerate detects the difference and this test fails - loudly, in CI, in
    seconds, instead of silently, in an ingest, after seven minutes.
    """
    from alembic.autogenerate import compare_metadata
    from alembic.migration import MigrationContext

    from backend.app.database import Base

    # Load every model so Base.metadata is complete. A model that was never
    # imported is invisible to the comparison - and autogenerate would conclude
    # its table is surplus and write a migration that DROPS it.
    from backend.app import features_models, models  # noqa: F401

    with engine.connect() as conn:
        ctx = MigrationContext.configure(conn, opts={"compare_type": True})
        diff = compare_metadata(ctx, Base.metadata)

    # Filter out the sequence noise Postgres reports for SERIAL columns.
    real = [d for d in diff if not (isinstance(d, tuple) and "sequence" in str(d[0]))]

    assert not real, (
        "The models and the database have DRIFTED. Someone changed a model without "
        "writing a migration.\n\n"
        f"Differences: {real}\n\n"
        "Fix:  alembic revision --autogenerate -m 'describe the change'\n"
        "      alembic upgrade head\n\n"
        "This is the exact failure that broke this build twice. Do not paper over "
        "it by dropping the table."
    )


def test_every_not_null_column_has_a_server_default() -> None:
    """A NOT NULL column with a PYTHON-only default cannot be added to a live table.

    THIS TEST EXISTS BECAUSE ALEMBIC'S FIRST AUTOGENERATED MIGRATION WAS BROKEN.

    It produced:

        ALTER TABLE daily_features ADD COLUMN session_count INTEGER NOT NULL

    which succeeds on an EMPTY table and fails on a POPULATED one:

        IntegrityError: column "session_count" contains null values

    ...because the 330,452 existing rows would all be NULL in the new column. The
    cause: the models used `default=0`, which is a PYTHON-side default the ORM applies
    at insert time. The database column had no DEFAULT clause at all. On a dev machine
    with an empty table the migration passes; on real data it does not - the worst
    possible failure mode, because it looks fine right up until it is expensive.

    THE RULE, NOT A LIST.

    An earlier version of this test carried a hand-maintained allowlist of thirty-odd
    columns that were "legitimately" NOT NULL without a default. That list broke the
    moment two new tables were added - which is precisely the failure mode I had just
    finished criticising elsewhere in this codebase. A list a human maintains is a
    list a human forgets.

    So it now checks the actual rule, which is derivable:

        A NOT NULL column needs a SERVER default IF AND ONLY IF the model declares a
        PYTHON default for it.

    If the model says `default=0`, the ORM will happily insert rows without that
    column - so the DATABASE must know the default too, or an ALTER on a populated
    table has nothing to backfill with.

    If the model declares NO default (user_id, email, hashed_password, an event's
    GUID), the column is genuinely REQUIRED. Nothing may be invented for it, and a
    silent default would be a bug rather than a convenience: defaulting an event's
    identifier would mean quietly inventing an identity.
    """
    from backend.app.database import Base
    from backend.app import features_models, models  # noqa: F401

    insp = inspect(engine)
    live = {
        t: {c["name"]: c for c in insp.get_columns(t)}
        for t in insp.get_table_names()
        if t != "alembic_version"
    }

    offenders: list[str] = []
    for table in Base.metadata.sorted_tables:
        cols = live.get(table.name)
        if cols is None:
            continue  # table not migrated yet; test_models_and_database_have_not_drifted owns that

        for col in table.columns:
            if col.nullable or col.primary_key:
                continue

            # The model declares a Python-side default but no server-side one.
            # That is exactly the combination that breaks ALTER on live data.
            python_default = col.default is not None
            server_default = col.server_default is not None

            if python_default and not server_default:
                offenders.append(f"{table.name}.{col.name}")

            # And the DATABASE must actually have it, not just the model.
            if server_default and cols.get(col.name, {}).get("default") is None:
                offenders.append(f"{table.name}.{col.name} (model has it, DB does not)")

    assert not offenders, (
        "These NOT NULL columns have a PYTHON default but no SERVER default:\n\n"
        + "\n".join(f"    {o}" for o in offenders)
        + "\n\nThe ORM will insert rows without them, so the DATABASE must know the "
          "default too. Without it, ALTER TABLE ADD COLUMN on a populated table fails "
          "with 'contains null values' - and it will pass on your empty dev database "
          "right up until it hits the real one.\n\n"
          "Add server_default= to the model, then regenerate the migration."
    )


def test_migration_is_reversible() -> None:
    """Every migration must have a working downgrade.

    A migration you cannot reverse is a one-way door. If it corrupts production at
    3am, "we'll roll forward" is not a plan, it is a hope. Alembic gives you
    downgrade() for free - but only if someone checks that it was actually written,
    which autogenerate does not guarantee for anything non-trivial.
    """
    from alembic.config import Config
    from alembic.script import ScriptDirectory

    from backend.app.schema import PROJECT_ROOT

    cfg = Config(str(PROJECT_ROOT / "alembic.ini"))
    cfg.set_main_option("script_location", str(PROJECT_ROOT / "migrations"))
    scripts = ScriptDirectory.from_config(cfg)

    revisions = list(scripts.walk_revisions())
    assert revisions, "there are no migrations at all"

    versions = PROJECT_ROOT / "migrations" / "versions"
    files = {f: f.read_text() for f in versions.glob("*.py")}

    for rev in revisions:
        # Find the file by the revision it DECLARES, not by its filename. Alembic
        # does not require the two to match.
        #
        # And match BOTH forms it can take, because autogenerate writes
        #     revision: str = '3c670d1086a0'
        # while a hand-written migration usually writes
        #     revision = "zz01servdef"
        # An earlier version of this test only matched the second, and failed on a
        # perfectly valid autogenerated migration.
        pattern = re.compile(
            rf"^revision(?::\s*str)?\s*=\s*['\"]{re.escape(rev.revision)}['\"]",
            re.M,
        )
        matches = [f for f, body in files.items() if pattern.search(body)]
        assert matches, f"migration file missing for revision {rev.revision}"

        body = files[matches[0]]
        assert "def downgrade()" in body, (
            f"migration {rev.revision} has no downgrade(). "
            "A migration you cannot reverse is a one-way door - if it corrupts "
            "production at 3am, 'we'll roll forward' is a hope, not a plan."
        )
        # An empty downgrade is WORSE than none. It lies: it claims to be
        # reversible, so the rollback "succeeds" and leaves the schema untouched.
        after = body.split("def downgrade()")[1]
        assert "op." in after or "exec_driver_sql" in after, (
            f"migration {rev.revision} has an EMPTY downgrade(). That is a lie - "
            "the rollback silently succeeds and changes nothing."
        )


def test_the_database_actually_has_every_default_the_models_declare() -> None:
    """The invariant is about the DATABASE, not about any particular migration.

    THIS TEST REPLACED ONE THAT WAS ASKING THE WRONG QUESTION.

    The previous version asserted that the zz01 server-defaults migration listed every
    column the models declare a server_default for. That passed - until two new tables
    were added, and then it failed, because zz01 is a HISTORICAL SNAPSHOT. It fixed
    the databases that had been adopted from the old create_all() world. Columns added
    afterwards get their defaults in their own migrations, and they should.

    The test was checking an implementation detail (WHICH migration did it) instead of
    the thing that actually matters (the database HAS it). So it broke on a change
    that was entirely correct, which is the definition of a bad test: it cost
    attention and protected nothing.

    The real invariant, and the one that would actually bite:

        every column the MODEL declares a server_default for must HAVE that default
        in the live database

    ...because that is what makes ALTER TABLE ADD COLUMN survive contact with
    330,452 rows. It does not matter which migration put it there.
    """
    from backend.app.database import Base
    from backend.app import features_models, models  # noqa: F401

    insp = inspect(engine)
    live = {
        t: {c["name"]: c for c in insp.get_columns(t)}
        for t in insp.get_table_names()
    }

    missing: list[str] = []
    for table in Base.metadata.sorted_tables:
        cols = live.get(table.name)
        if cols is None:
            continue
        for col in table.columns:
            if col.server_default is None:
                continue
            if cols.get(col.name, {}).get("default") is None:
                missing.append(f"{table.name}.{col.name}")

    assert not missing, (
        f"{len(missing)} column(s) declare a server_default in the MODEL but do NOT "
        f"have one in the DATABASE:\n\n"
        + "\n".join(f"    {m}" for m in missing)
        + "\n\nThe next ALTER TABLE ADD COLUMN against those tables will fail on "
          "populated data with 'contains null values'. Generate a migration:\n"
          "    alembic revision --autogenerate -m 'add server defaults'\n"
          "    alembic upgrade head"
    )


def test_clear_all_can_actually_clear_every_table() -> None:
    """clear_all() must know about EVERY table with a foreign key to employees.

    THIS TEST EXISTS BECAUSE I MADE THE SAME BUG TWICE, IN THE SAME FUNCTION,
    UNDERNEATH A COMMENT DESCRIBING IT.

    clear_all() used to be a hand-written tuple of models, deleted in order. Its
    docstring said, in as many words:

        "This was a real bug: the first version of this list omitted them, and
         re-running ingestion after building features died with a
         ForeignKeyViolation. Any table pointing at employees has to be cleared
         here, whichever phase created it."

    Then I added the `alerts` table with a foreign key to employees, did not add it
    to the list, and ingestion died with:

        ForeignKeyViolation: update or delete on table "employees" violates
        constraint "alerts_user_id_fkey" on table "alerts"

    Writing "REMEMBER TO UPDATE THIS" at the top of a list has never once worked,
    because the person adding the table is not reading that file.

    clear_all() is now derived from Base.metadata.sorted_tables, which IS the
    schema and therefore cannot be out of date. This test asserts the property that
    matters: nothing that references employees is left behind.
    """
    from backend.app.database import Base
    from backend.app import features_models, models  # noqa: F401

    KEEP = {"security_users", "audit_logs", "alembic_version"}

    # Every table with an FK to employees.
    referencing = set()
    for table in Base.metadata.sorted_tables:
        for fk in table.foreign_keys:
            if fk.column.table.name == "employees":
                referencing.add(table.name)

    assert referencing, "no table references employees - that cannot be right"

    # clear_all deletes everything in metadata except KEEP. So the only way a
    # referencing table survives is if it is in KEEP - which would be a bug.
    stranded = referencing & KEEP
    assert not stranded, (
        f"{stranded} reference employees but are on clear_all's KEEP list. "
        "DELETE FROM employees will fail with a ForeignKeyViolation."
    )

    # And KEEP must not name a table that no longer exists - a stale exclusion is a
    # table that silently starts being wiped on the next import.
    known = {t.name for t in Base.metadata.sorted_tables}
    ghosts = KEEP - known - {"alembic_version"}  # alembic_version isn't in metadata
    assert not ghosts, (
        f"clear_all's KEEP list names tables that do not exist: {ghosts}. "
        "If one was renamed, it is now being WIPED on every re-ingest."
    )