"""alerts and alert notes

Revision ID: 05c0619526ea
Revises: zz01servdef
Create Date: 2026-07-13 17:30:01.627338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c0619526ea'
down_revision: Union[str, None] = 'zz01servdef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('alert_date', sa.Date(), nullable=False),
    sa.Column('severity', sa.Enum('INFORMATIONAL', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertseverity', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ACKNOWLEDGED', 'INVESTIGATING', 'ESCALATED', 'RESOLVED_TRUE_POSITIVE', 'RESOLVED_FALSE_POSITIVE', name='alertstatus', native_enum=False, length=30), server_default='NEW', nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('ml_probability', sa.Float(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('top_features', sa.JSON(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['security_users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['security_users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['security_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['employees.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'alert_date', name='uq_alert_user_day')
    )
    op.create_index(op.f('ix_alerts_alert_date'), 'alerts', ['alert_date'], unique=False)
    op.create_index(op.f('ix_alerts_assigned_to_id'), 'alerts', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_alerts_risk_score'), 'alerts', ['risk_score'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_triage', 'alerts', ['status', 'severity', 'alert_date'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('alert_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_id'], ['security_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_notes_alert_id'), 'alert_notes', ['alert_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_notes_alert_id'), table_name='alert_notes')
    op.drop_table('alert_notes')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index('ix_alerts_triage', table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_risk_score'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_assigned_to_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_date'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###