"""auth hardening lockout and password rotation

Revision ID: 0e25a229f190
Revises: 3c670d1086a0
Create Date: 2026-07-13 15:16:57.937459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e25a229f190'
down_revision: Union[str, None] = '3c670d1086a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_users', sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('security_users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('security_users', sa.Column('password_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('security_users', 'password_changed_at')
    op.drop_column('security_users', 'locked_until')
    op.drop_column('security_users', 'failed_login_attempts')
    # ### end Alembic commands ###