"""server defaults for role and alert json

Revision ID: 21faf58d595b
Revises: 05c0619526ea
Create Date: 2026-07-13 17:39:12.449432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21faf58d595b'
down_revision: Union[str, None] = '05c0619526ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'components',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default='{}',
               existing_nullable=False)
    op.alter_column('alerts', 'top_features',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default='[]',
               existing_nullable=False)
    op.alter_column('security_users', 'role',
               existing_type=postgresql.ENUM('SECURITY_ANALYST', 'SOC_ENGINEER', 'SECURITY_MANAGER', 'ADMINISTRATOR', name='user_role'),
               server_default='SECURITY_ANALYST',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('security_users', 'role',
               existing_type=postgresql.ENUM('SECURITY_ANALYST', 'SOC_ENGINEER', 'SECURITY_MANAGER', 'ADMINISTRATOR', name='user_role'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('alerts', 'top_features',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('alerts', 'components',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###