"""initial schema

Revision ID: 3c670d1086a0
Revises: 
Create Date: 2026-07-13 15:08:16.365974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c670d1086a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('employee_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('business_unit', sa.String(length=100), nullable=True),
    sa.Column('functional_unit', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('team', sa.String(length=100), nullable=True),
    sa.Column('supervisor', sa.String(length=255), nullable=True),
    sa.Column('psych_o', sa.Integer(), nullable=True),
    sa.Column('psych_c', sa.Integer(), nullable=True),
    sa.Column('psych_e', sa.Integer(), nullable=True),
    sa.Column('psych_a', sa.Integer(), nullable=True),
    sa.Column('psych_n', sa.Integer(), nullable=True),
    sa.Column('is_insider', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('insider_scenario', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    op.create_index(op.f('ix_employees_is_insider'), 'employees', ['is_insider'], unique=False)
    op.create_index(op.f('ix_employees_role'), 'employees', ['role'], unique=False)
    op.create_index(op.f('ix_employees_team'), 'employees', ['team'], unique=False)
    op.create_table('security_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SECURITY_ANALYST', 'SOC_ENGINEER', 'SECURITY_MANAGER', 'ADMINISTRATOR', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_users_email'), 'security_users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('security_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['security_user_id'], ['security_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_security_user_id'), 'audit_logs', ['security_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('daily_features',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('logon_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('after_hours_logon_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('weekend_logon_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('distinct_pcs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('session_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_session_hours', sa.Float(), server_default='0', nullable=False),
    sa.Column('new_pc_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('used_supervisor_pc', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('usb_connect_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('after_hours_usb_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('weekend_usb_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('file_event_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('exe_file_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('doc_file_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('zip_file_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('email_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('external_email_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_email_size', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('total_attachments', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_recipients', sa.Integer(), server_default='0', nullable=False),
    sa.Column('http_total_visits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('job_site_visits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('wikileaks_visits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cloud_storage_visits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('hacking_site_visits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('distinct_domains', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_malicious', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['employees.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_features_date'), 'daily_features', ['date'], unique=False)
    op.create_index(op.f('ix_daily_features_is_malicious'), 'daily_features', ['is_malicious'], unique=False)
    op.create_index(op.f('ix_daily_features_user_id'), 'daily_features', ['user_id'], unique=False)
    op.create_index('ix_features_user_date', 'daily_features', ['user_id', 'date'], unique=True)
    op.create_table('device_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('pc', sa.String(length=20), nullable=False),
    sa.Column('activity', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['employees.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_events_pc'), 'device_events', ['pc'], unique=False)
    op.create_index(op.f('ix_device_events_timestamp'), 'device_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_device_events_user_id'), 'device_events', ['user_id'], unique=False)
    op.create_index('ix_device_user_time', 'device_events', ['user_id', 'timestamp'], unique=False)
    op.create_table('email_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('pc', sa.String(length=20), nullable=False),
    sa.Column('size', sa.Integer(), server_default='0', nullable=False),
    sa.Column('attachment_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('recipient_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('has_external_recipient', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['employees.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_events_has_external_recipient'), 'email_events', ['has_external_recipient'], unique=False)
    op.create_index(op.f('ix_email_events_pc'), 'email_events', ['pc'], unique=False)
    op.create_index(op.f('ix_email_events_timestamp'), 'email_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_email_events_user_id'), 'email_events', ['user_id'], unique=False)
    op.create_index('ix_email_user_time', 'email_events', ['user_id', 'timestamp'], unique=False)
    op.create_table('file_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('pc', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_extension', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['employees.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_events_file_extension'), 'file_events', ['file_extension'], unique=False)
    op.create_index(op.f('ix_file_events_pc'), 'file_events', ['pc'], unique=False)
    op.create_index(op.f('ix_file_events_timestamp'), 'file_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_file_events_user_id'), 'file_events', ['user_id'], unique=False)
    op.create_index('ix_file_user_time', 'file_events', ['user_id', 'timestamp'], unique=False)
    op.create_table('http_daily_summary',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_visits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('job_site_visits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('wikileaks_visits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cloud_storage_visits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('hacking_site_visits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('distinct_domains', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['employees.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_http_daily_summary_date'), 'http_daily_summary', ['date'], unique=False)
    op.create_index(op.f('ix_http_daily_summary_user_id'), 'http_daily_summary', ['user_id'], unique=False)
    op.create_index('ix_http_user_date', 'http_daily_summary', ['user_id', 'date'], unique=True)
    op.create_table('insider_ground_truth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('scenario', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['employees.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insider_ground_truth_scenario'), 'insider_ground_truth', ['scenario'], unique=False)
    op.create_index(op.f('ix_insider_ground_truth_user_id'), 'insider_ground_truth', ['user_id'], unique=False)
    op.create_table('logon_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('pc', sa.String(length=20), nullable=False),
    sa.Column('activity', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['employees.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logon_events_pc'), 'logon_events', ['pc'], unique=False)
    op.create_index(op.f('ix_logon_events_timestamp'), 'logon_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_logon_events_user_id'), 'logon_events', ['user_id'], unique=False)
    op.create_index('ix_logon_user_time', 'logon_events', ['user_id', 'timestamp'], unique=False)
    op.create_table('user_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('training_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('mean_logon_count', sa.Float(), server_default='0', nullable=False),
    sa.Column('std_logon_count', sa.Float(), server_default='0', nullable=False),
    sa.Column('mean_after_hours_logon', sa.Float(), server_default='0', nullable=False),
    sa.Column('std_after_hours_logon', sa.Float(), server_default='0', nullable=False),
    sa.Column('mean_usb_connect', sa.Float(), server_default='0', nullable=False),
    sa.Column('std_usb_connect', sa.Float(), server_default='0', nullable=False),
    sa.Column('mean_file_events', sa.Float(), server_default='0', nullable=False),
    sa.Column('std_file_events', sa.Float(), server_default='0', nullable=False),
    sa.Column('mean_external_email', sa.Float(), server_default='0', nullable=False),
    sa.Column('std_external_email', sa.Float(), server_default='0', nullable=False),
    sa.Column('mean_http_visits', sa.Float(), server_default='0', nullable=False),
    sa.Column('std_http_visits', sa.Float(), server_default='0', nullable=False),
    sa.Column('ever_used_usb', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ever_worked_after_hours', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['employees.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_baselines_user_id'), 'user_baselines', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_baselines_user_id'), table_name='user_baselines')
    op.drop_table('user_baselines')
    op.drop_index('ix_logon_user_time', table_name='logon_events')
    op.drop_index(op.f('ix_logon_events_user_id'), table_name='logon_events')
    op.drop_index(op.f('ix_logon_events_timestamp'), table_name='logon_events')
    op.drop_index(op.f('ix_logon_events_pc'), table_name='logon_events')
    op.drop_table('logon_events')
    op.drop_index(op.f('ix_insider_ground_truth_user_id'), table_name='insider_ground_truth')
    op.drop_index(op.f('ix_insider_ground_truth_scenario'), table_name='insider_ground_truth')
    op.drop_table('insider_ground_truth')
    op.drop_index('ix_http_user_date', table_name='http_daily_summary')
    op.drop_index(op.f('ix_http_daily_summary_user_id'), table_name='http_daily_summary')
    op.drop_index(op.f('ix_http_daily_summary_date'), table_name='http_daily_summary')
    op.drop_table('http_daily_summary')
    op.drop_index('ix_file_user_time', table_name='file_events')
    op.drop_index(op.f('ix_file_events_user_id'), table_name='file_events')
    op.drop_index(op.f('ix_file_events_timestamp'), table_name='file_events')
    op.drop_index(op.f('ix_file_events_pc'), table_name='file_events')
    op.drop_index(op.f('ix_file_events_file_extension'), table_name='file_events')
    op.drop_table('file_events')
    op.drop_index('ix_email_user_time', table_name='email_events')
    op.drop_index(op.f('ix_email_events_user_id'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_timestamp'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_pc'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_has_external_recipient'), table_name='email_events')
    op.drop_table('email_events')
    op.drop_index('ix_device_user_time', table_name='device_events')
    op.drop_index(op.f('ix_device_events_user_id'), table_name='device_events')
    op.drop_index(op.f('ix_device_events_timestamp'), table_name='device_events')
    op.drop_index(op.f('ix_device_events_pc'), table_name='device_events')
    op.drop_table('device_events')
    op.drop_index('ix_features_user_date', table_name='daily_features')
    op.drop_index(op.f('ix_daily_features_user_id'), table_name='daily_features')
    op.drop_index(op.f('ix_daily_features_is_malicious'), table_name='daily_features')
    op.drop_index(op.f('ix_daily_features_date'), table_name='daily_features')
    op.drop_table('daily_features')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_security_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_security_users_email'), table_name='security_users')
    op.drop_table('security_users')
    op.drop_index(op.f('ix_employees_team'), table_name='employees')
    op.drop_index(op.f('ix_employees_role'), table_name='employees')
    op.drop_index(op.f('ix_employees_is_insider'), table_name='employees')
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###