"""Schema management. One door in, and it is Alembic.

WHY THIS MODULE EXISTS
----------------------
Before this, four different places called `Base.metadata.create_all()`:

    backend/app/main.py          on application startup
    backend/app/ingestion.py     inside recreate_derived_tables()
    backend/app/features.py      inside recreate_feature_tables()
    scripts/ingest_cert.py       before ingesting

create_all() creates tables that do not exist. It does NOT alter tables that do.
So a new column on an existing model produced a clean, silent, successful startup -
followed by a crash on the first INSERT:

    psycopg2.errors.UndefinedColumn:
      column "session_count" of relation "daily_features" does not exist

That happened TWICE. The workaround both times was to DROP the table and rebuild
it. That is survivable for DERIVED tables, and unthinkable for anything else - you
cannot drop `employees` to add a column to it, and you certainly cannot drop
`logon_events` and re-stream 32 million rows because someone added a boolean.

Alembic replaces all of it. The database carries a version number. Schema changes
are files in git that someone can read and review. They ALTER in place. Nothing is
dropped, nothing is lost.

THE ONE THING THAT ALMOST BROKE THIS
------------------------------------
Alembic's first autogenerated migration produced:

    ALTER TABLE daily_features ADD COLUMN session_count INTEGER NOT NULL

which works perfectly on an empty table and FAILS on a populated one - every
existing row would be NULL in the new column, violating NOT NULL. On a dev database
with no data it passes. On 330,452 real rows it does not.

The cause was that the models used `default=0`, which is a PYTHON-side default the
ORM applies at insert time. The database column had no DEFAULT clause at all. Fixed
by adding `server_default` to all 52 such columns, so the DDL carries the default
and the database backfills existing rows itself.

That is the difference between a migration that works in development and one that
works in production, and it is exactly the class of bug that only shows up when it
is expensive.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

from sqlalchemy import inspect

from backend.app.database import engine

PROJECT_ROOT = Path(__file__).resolve().parents[2]


def schema_is_current() -> tuple[bool, str]:
    """Is the database at the latest migration?

    Returns (ok, message). Cheap - reads one row from alembic_version.
    """
    insp = inspect(engine)
    if not insp.has_table("alembic_version"):
        return False, (
            "The database has no alembic_version table, which means it was never "
            "migrated.\n\n    Run:  alembic upgrade head"
        )

    with engine.connect() as conn:
        from sqlalchemy import text

        current = conn.execute(text("SELECT version_num FROM alembic_version")).scalar()

    head = _head_revision()
    if current != head:
        return False, (
            f"The database is at migration {current}, but the code expects {head}.\n\n"
            f"    Run:  alembic upgrade head"
        )
    return True, f"schema at {current}"


def _head_revision() -> str | None:
    """The newest migration in migrations/versions, per Alembic itself."""
    from alembic.config import Config
    from alembic.script import ScriptDirectory

    cfg = Config(str(PROJECT_ROOT / "alembic.ini"))
    cfg.set_main_option("script_location", str(PROJECT_ROOT / "migrations"))
    return ScriptDirectory.from_config(cfg).get_current_head()


def upgrade_to_head() -> None:
    """Run `alembic upgrade head` in-process.

    Used by the test suite and by the ingestion scripts, so that a fresh database
    gets a correct schema without anyone having to remember a second command.
    """
    from alembic import command
    from alembic.config import Config

    cfg = Config(str(PROJECT_ROOT / "alembic.ini"))
    cfg.set_main_option("script_location", str(PROJECT_ROOT / "migrations"))

    from backend.app.config import get_settings

    cfg.set_main_option("sqlalchemy.url", get_settings().DATABASE_URL)

    command.upgrade(cfg, "head")

    # The migration ran through its own connections. Ours are now holding a stale
    # view of the schema, and the next query would fail with "column does not
    # exist" against a column that demonstrably does. Dispose the pool.
    engine.dispose()