"""PDF and Excel export endpoints."""

from __future__ import annotations

from datetime import datetime, timezone

import pandas as pd
from flask import Blueprint, Response, jsonify, request

from app.auth import current_username, require_auth
from app.ml import engine as eng
from app.ml.features import BEHAVIOURAL_COLUMNS, FEATURE_LABELS
from app.models import record_audit
from app.services.directory import get_directory
from app.services.reports import build_excel, build_investigation_pdf

bp = Blueprint("export", __name__, url_prefix="/api/v1/export")


def _engine_or_503():
    try:
        return eng.get_engine(), None
    except eng.ModelNotTrained as exc:
        return None, (jsonify({"error": "model not trained", "detail": str(exc)}), 503)


def _attachment(payload: bytes, filename: str, mimetype: str) -> Response:
    return Response(
        payload,
        mimetype=mimetype,
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
            "Content-Length": str(len(payload)),
        },
    )


@bp.get("/pdf")
@require_auth("analyst")
def export_pdf():
    """Investigation case file for one subject. `?user=ID&day=YYYY-MM-DD`"""
    engine, err = _engine_or_503()
    if err:
        return err

    user = (request.args.get("user") or "").strip()
    if not user:
        return jsonify({"error": "query parameter 'user' is required"}), 400

    day = request.args.get("day")
    case = engine.investigate(user, day)
    if not case:
        return jsonify({"error": f"no activity for {user}"
                                 + (f" on {day}" if day else "")}), 404

    case["identity"] = get_directory().get(user, {})
    analyst = current_username()
    pdf = build_investigation_pdf(case, analyst=analyst)
    record_audit(analyst, "EXPORT_PDF", user, f"day={case['day']}")

    return _attachment(pdf, f"Investigation_Report_{user}_{case['day']}.pdf",
                       "application/pdf")


@bp.get("/excel")
@require_auth("viewer")
def export_excel():
    """Activity and risk workbook.

    Optional filters: `?user=ID` for a single subject, `?severity=HIGH`,
    `?min_score=60`, `?limit=5000`.
    """
    engine, err = _engine_or_503()
    if err:
        return err

    user = (request.args.get("user") or "").strip()
    severity = (request.args.get("severity") or "").strip().upper()
    min_score = request.args.get("min_score", type=float)
    limit = min(int(request.args.get("limit", 5000)), 50000)

    df = engine.df.copy()
    if user:
        df = df[df["user"] == user]
        if df.empty:
            return jsonify({"error": f"no activity for {user}"}), 404
    if severity:
        df = df[df["severity"] == severity]
    if min_score is not None:
        df = df[df["risk_score"] >= min_score]

    df = df.sort_values("risk_score", ascending=False).head(limit)
    directory = get_directory()

    detail_cols = ["user", "day_str", "risk_score", "ueba_score", "ml_probability",
                   "severity", "is_insider"] + BEHAVIOURAL_COLUMNS
    detail = df[detail_cols].rename(
        columns={"day_str": "day", "is_insider": "confirmed_insider"}
    ).round(3)
    detail.insert(1, "name", detail["user"].map(
        lambda u: directory.get(u, {}).get("name", "")))

    summary = engine.users().copy()
    if user:
        summary = summary[summary["user"] == user]
    summary["name"] = summary["user"].map(lambda u: directory.get(u, {}).get("name", ""))
    summary["department"] = summary["user"].map(
        lambda u: directory.get(u, {}).get("department", ""))
    summary = summary[["user", "name", "department", "severity", "peak_risk",
                       "mean_risk", "latest_risk", "active_days", "flagged_days",
                       "confirmed_days"]].round(2)

    stats = engine.stats()
    overview = pd.DataFrame(
        [
            ("Report generated (UTC)", datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")),
            ("Generated by", current_username()),
            ("Filter — user", user or "all"),
            ("Filter — severity", severity or "all"),
            ("Filter — min score", min_score if min_score is not None else "none"),
            ("Rows exported", len(detail)),
            ("Monitored users", stats["total_users"]),
            ("Observation window", " to ".join(stats["date_range"])),
            ("Open alerts", stats["open_alerts"]),
            ("Model", stats["model"]["name"]),
            ("Model PR-AUC", stats["model"]["pr_auc"]),
            ("Model recall", stats["model"]["recall"]),
        ],
        columns=["Field", "Value"],
    )

    glossary = pd.DataFrame(
        [(k, v) for k, v in FEATURE_LABELS.items()], columns=["feature", "description"]
    )

    payload = build_excel(
        {
            "Overview": overview,
            "Risk Summary": summary,
            "Activity Detail": detail,
            "Feature Glossary": glossary,
        }
    )
    record_audit(current_username(), "EXPORT_EXCEL", user or "all",
                 f"rows={len(detail)}")

    stamp = datetime.now(timezone.utc).strftime("%Y%m%d")
    name = f"ITBIS_Risk_Export_{user or 'all'}_{stamp}.xlsx"
    return _attachment(
        payload, name,
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    )
